

spring.data.mongodb.uri=mongodb+srv://bhavitkanthalia16:krfKKUtrhLJ22ldb@backend.gysmq9b.mongodb.net/server_backend?retryWrites=true&w=majority
spring.data.mongodb.database=server_backend
#net.ipv4.tcp_keepalive_time = 12000
#spring.data.mongodb.option.socket.connectTimeout=10000
#spring.data.mongodb.option.socket.readTimeout= 5000

server.port  = 8080
Access-Control-Allow-Origin: *
logging.level.org.springframework.security=DEBUG

cloudinary.cloud-name=dwoc1tjjn
cloudinary.api-key=324468397149782
cloudinary.api-secret=9D7K4W9syq3mj09VZdYy-VOPfc8

# VAPID keys for Web Push notifications (generated 2026-06-27)
vapid.public-key=BK1ftcp44rv2lzwwdP7YOoxU2e8qvMJA9TBu_5Zp5t24PxXPIjnfBdOvZDhgWGoZr_k2URQgw6y7tKKfjJ7ltug
vapid.private-key=u7g0ZtHRQjUMU0oA05Ry6J8SWE1KUZkdHGV6vt-UOq8